### PR TITLE
Fix Ditto

### LINKED ISSUE #490: Capturing Ditto causes error
The program stopped listing my Pokemon after a caught a Ditto. Below is what I'm getting:

[20:22:47]: Successfully logged in. Welcome, [redacted].
[20:22:47]: Stats: Lvl 33 Valor player.
[20:22:47]: Pokédex - Types Caught: 143, Total Pokémon Caught: 8950, Total Current Pokémon: 705 (+9 Eggs)
[20:22:47]: Current version: v0.1.4
[20:22:47]: Latest version from server: v0.1.4
[20:22:47]: Highest Duel Ability: Snorlax with Lick and Hyper Beam has 21209394375
[20:22:47]: Highest Gym Offense: Dragonite with Dragon Breath and Hyper Beam has 467062.5
[20:22:47]: Highest Gym Defense: Lapras with Ice Shard and Ice Beam has 9490026563
[20:22:47]: Load saved locations from file.
[20:22:48]: java.lang.NullPointerException
[20:22:48]: 	at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:89)
[20:22:48]: 	at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:75)
[20:22:48]: 	at me.corriekay.pokegoutil.data.enums.PokeColumn$13.get(PokeColumn.java:106)
[20:22:48]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.lambda$updateTableData$0(PokemonTableModel.java:48)
[20:22:48]: 	at java.util.ArrayList.forEach(Unknown Source)
[20:22:48]: 	at java.util.Collections$SynchronizedCollection.forEach(Unknown Source)
[20:22:48]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.updateTableData(PokemonTableModel.java:43)
[20:22:48]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTable.constructNewTableModel(PokemonTable.java:108)
[20:22:48]: 	at me.corriekay.pokegoutil.windows.PokemonTab.refreshList(PokemonTab.java:1040)
[20:22:48]: 	at me.corriekay.pokegoutil.windows.PokemonTab.lambda$new$10(PokemonTab.java:248)
[20:22:48]: 	at me.corriekay.pokegoutil.utils.helpers.LDocumentListener$1.lambda$changedUpdate$0(LDocumentListener.java:58)
[20:22:48]: 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[20:22:48]: 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[20:22:48]: 	at java.awt.EventQueue.access$500(Unknown Source)
[20:22:48]: 	at java.awt.EventQueue$3.run(Unknown Source)
[20:22:48]: 	at java.awt.EventQueue$3.run(Unknown Source)
[20:22:48]: 	at java.security.AccessController.doPrivileged(Native Method)
[20:22:48]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[20:22:48]: 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[20:22:48]: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[20:22:48]: 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[20:22:48]: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[20:22:48]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[20:22:48]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[20:22:48]: 	at java.awt.EventDispatchThread.run(Unknown Source)

### PR DESCRIPTION
**Pull request by Wolfsblvt**
Fixes #490.

### CODE REVIEW

File: src/me/corriekay/pokegoutil/utils/Utilities.java [hunk 1]
```diff
@@ -45,13 +45,14 @@ public static boolean isEven(long i) {
 
     /**
      * Takes to numbers and creates a decimal percentage of it (like 0.7542).
```
Comment (FernandoTBarros) [inline src/me/corriekay/pokegoutil/utils/Utilities.java:47]: Doen's about this commit but maybe there is a typo here? "Takes TWO..." instead of "Takes to"?

**Review by FernandoTBarros — APPROVED** [review]
Updating libs and bringing Ditto to game!
